blank_issues_enabled: false
contact_links:
  - name: Steam Store Page
    url: https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
    about: View the Steam Store page for the software.
  - name: Steam Workshop
    url: https://steamcommunity.com/app/2516360/workshop/
    about: View the Steam Workshop page for the software.
  - name: Discord
    url: https://discord.gg/8ppmspR6Wh
    about: Join the Discord server for Nonsensical Video Generator.
